name: Generate changelog preview

on:
  workflow_call:
    inputs:
      cliff_config_url:
        type: string
        description: URL to a git-cliff configuration file
        default: https://raw.githubusercontent.com/holochain/release-integration/refs/heads/main/pre-1.0-cliff.toml

jobs:
  changelog-preview-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR commits only
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: ${{ github.event.pull_request.commits }}
          sparse-checkout: ''
          sparse-checkout-cone-mode: false

      - name: Checkout all tags
        run: git fetch --tags

      - name: Install git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@2.9.1

      - name: Run git cliff
        run: |
          git cliff \
            --bump \
            --config-url="${{ inputs.cliff_config_url }}" \
            --strip=all \
            --output=PR_CHANGELOG.md

      - name: Add changelog preview as comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.html_url }} \
            --body="$(printf 'The following will be added to the changelog\n\n---\n\n'; cat PR_CHANGELOG.md)" \
            --edit-last \
            --create-if-none
