name: prepare-release.yml
on:
  workflow_call:
    inputs:
      cliff_config:
        type: string
        description: "Path or URL to a git-cliff configuration file"
        default: "https://raw.githubusercontent.com/holochain/release-integration/refs/heads/main/pre-1.0-cliff.toml"
        required: true
      force_version:
        type: string
        description: "Specify the semver version for the next release, to override the default semver bump"
        default: ""
        required: false
    secrets:
        HRA2_GITHUB_TOKEN:
          description: "GitHub token for Holochain Release Automation"
          required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@2.9.1

      - name: Install cargo-workspaces
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-workspaces@0.4.0

      - name: Install cargo-semver-checks
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-semver-checks@0.41.0

      - name: Install holochain_release_util
        # TODO Install from a release once available
        run: cargo install --git https://github.com/holochain/release-integration.git --branch prepare-publish holochain_release_util

      - name: Prepare release
        run: |
          holochain_release_util generate --cliff-config "${{ inputs.cliff_config }}" \
            --force-version "${{ inputs.force_version }}"

      - name: Create a release pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.HRA2_GITHUB_TOKEN }}
          committer: "Holochain Release Automation <hra+gh@holochain.org>"
          title: "Prepare next release"
          commit-message: 'chore: Prepare next release'
          branch: "prepare-release"
          branch-suffix: "short-commit-hash"
          labels: "hra-release"
          team-reviewers: "holochain/holochain-devs"
