name: publish-release.yml
on:
  workflow_call:
    secrets:
      HRA2_GITHUB_TOKEN:
        description: "GitHub token for Holochain Release Automation"
        required: true
      HRA2_CRATES_IO_TOKEN:
        description: "Crates.io token for publishing Rust packages"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-workspaces
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-workspaces@0.4.0

      - name: Install holochain_release_util
        run: cargo install --git https://github.com/holochain/release-integration.git holochain_release_util

      # Note that if the HEAD commit did not come from a PR that was labeled with `hra-release`, this will be a no-op.
      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.HRA2_GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.HRA2_CRATES_IO_TOKEN }}
        run: |
          git config --local user.name "Holochain Release Automation"
          git config --local user.email "hra+gh@holochain.org"

          holochain_release_util publish
